Controllers/GradesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PAW_CATALOG_PROJ.Data;
using PAW_CATALOG_PROJ.Models;
using Microsoft.AspNetCore.Identity;

namespace PAW_CATALOG_PROJ.Controllers
{
    [Authorize]
    public class GradesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public GradesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Grades
        public async Task<IActionResult> Index(string? sortBy)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return Challenge();

            if (string.IsNullOrEmpty(user.Email))
                return Forbid();

            var appUser = await _context.AppUsers.FirstOrDefaultAsync(u => u.Email == user.Email);
            if (appUser == null)
                return Forbid();

            if (User.IsInRole("Profesor"))
            {
                return RedirectToAction("Index", "Enrollments");
            }

            if (User.IsInRole("Student"))
            {
                var gradesQuery = _context.Grades
                    .Include(g => g.Enrollment)
                        .ThenInclude(e => e.Course)
                    .Include(g => g.Enrollment)
                        .ThenInclude(e => e.Student)
                    .Where(g => g.Enrollment.StudentId == appUser.Id);

                gradesQuery = sortBy switch
                {
                    "grade" => gradesQuery.OrderByDescending(g => g.GradeValue),
                    "alphabetical" => gradesQuery.OrderBy(g => g.Enrollment.Course.CourseName),
                    _ => gradesQuery
                };

                var grades = await gradesQuery.ToListAsync();

                double overallAverage = (double)(grades.Any()
                    ? grades.Average(g => g.GradeValue)
                    : 0);

                var fixedYears = new int[] { 1, 2, 3 };

                var averagesForExistingYears = grades
                    .GroupBy(g => g.Enrollment.EnrollmentYear)
                    .Select(group => new
                    {
                        Year = group.Key,
                        Average = group.Average(g => g.GradeValue)
                    })
                    .ToList();

                var completedAveragesPerYear = fixedYears
                    .Select(year =>
                    {
                        var found = averagesForExistingYears.FirstOrDefault(a => a.Year == year.ToString());
                        return new
                        {
                            Year = year,
                            Average = found != null ? Math.Round(found.Average, 2) : 0
                        };
                    })
                    .ToList();

                ViewBag.OverallAverage = Math.Round(overallAverage, 2);
                ViewBag.AveragesPerYear = completedAveragesPerYear;
                ViewBag.Role = "Student";
                ViewBag.SortBy = sortBy;
                return View("StudentIndex", grades);
            }



            return Forbid();
        }



        [Authorize(Roles = "Profesor")]
        public async Task<IActionResult> Create(int? enrollmentId)
        {
            if (enrollmentId == null)
                return BadRequest();

            var enrollment = await _context.Enrollments
                .Include(e => e.Student)
                .Include(e => e.Course)
                .FirstOrDefaultAsync(e => e.Id == enrollmentId);

            if (enrollment == null)
                return NotFound();

            var grade = new Grade
            {
                EnrollmentId = enrollment.Id,
                DateRecorded = DateTime.Now
            };

            ViewData["EnrollmentInfo"] = $"{enrollment.Student.Name} - {enrollment.Course.CourseName}";

            return View(grade);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Profesor")]
        public async Task<IActionResult> Create([Bind("EnrollmentId,Title,GradeValue")] Grade grade)
        {

            Console.WriteLine($"{grade.GradeValue},{grade.EnrollmentId},{grade.Title}");
            Console.WriteLine($"************************************************");
            Console.WriteLine($"************************************************");
            Console.WriteLine($"************************************************");
            Console.WriteLine($"************************************************");
            Console.WriteLine($"************************************************");
            Console.WriteLine($"************************************************");

            if (ModelState.IsValid)
            {
                grade.DateRecorded = DateTime.Now; 

                _context.Grades.Add(grade);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Enrollments"); 
            }

          
            var enrollment = await _context.Enrollments
                .Include(e => e.Student)
                .Include(e => e.Course)
                .FirstOrDefaultAsync(e => e.Id == grade.EnrollmentId);

            if (enrollment == null)
                return NotFound();

            ViewData["EnrollmentInfo"] = $"{enrollment.Student.Email} - {enrollment.Course.CourseName}";

            return View(grade);
        }




        [Authorize(Roles = "Profesor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var grade = await _context.Grades.FindAsync(id);
            if (grade == null) return NotFound();

            ViewData["EnrollmentId"] = new SelectList(_context.Enrollments, "Id", "Id", grade.EnrollmentId);
            return View(grade);
        }

        [Authorize(Roles = "Profesor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GradeId,EnrollmentId,Title,GradeValue,MaxGrade,DateRecorded")] Grade grade)
        {
            if (id != grade.GradeId) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Grades.Any(e => e.GradeId == id))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["EnrollmentId"] = new SelectList(_context.Enrollments, "Id", "Id", grade.EnrollmentId);
            return View(grade);
        }

        [Authorize(Roles = "Profesor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var grade = await _context.Grades
                .Include(g => g.Enrollment)
                .FirstOrDefaultAsync(m => m.GradeId == id);

            if (grade == null) return NotFound();

            return View(grade);
        }

        [Authorize(Roles = "Profesor")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grade = await _context.Grades.FindAsync(id);
            if (grade != null)
                _context.Grades.Remove(grade);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/GroupsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PAW_CATALOG_PROJ.Data;
using PAW_CATALOG_PROJ.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PAW_CATALOG_PROJ.Controllers
{
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Groups->all groups
        public async Task<IActionResult> Index()
        {
            return View(await _context.Groups.ToListAsync());
        }

        // GET: Groups->search groups by group number   
        public async Task<IActionResult>  SearchGroups()
        {
             return View();
        }

        // POST: search groups by group number
        public async Task<IActionResult> ShowSearchedGroups(String SearchGroups)
        {
            return View("Index",await _context.Groups.Where(j => j.GroupNumber.Contains(SearchGroups))
                .ToListAsync());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Secretar")]
        public async Task<IActionResult> Create([Bind("Id,GroupNumber")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GroupNumber")] Group @group)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Groups.FindAsync(id);
            if (@group != null)
            {
                _context.Groups.Remove(@group);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> StudentList(int id)
        {
            var grupa = await _context.Groups.FirstOrDefaultAsync(g => g.Id == id);
            if (grupa == null)
            {
                return NotFound();
            }

           
            var studenti = await _context.Enrollments
                .Include(e => e.Student)
                .Where(e => e.GroupId == id)
                .Select(e => e.Student)
                .ToListAsync();

            ViewBag.GroupNumber = grupa.GroupNumber;

            return View(studenti);
        }


        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - PAW_CATALOG_PROJ</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/PAW_CATALOG_PROJ.styles.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom shadow-sm mb-4">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">PAW_CATALOG_PROJ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grades" asp-action="Index">Grades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="Index">Enrollments</a>
                        </li>
                        @if (User.IsInRole("Profesor") || User.IsInRole("Secretar"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted py-3">
        <div class="container text-center">
            &copy; 2025 - PAW_CATALOG_PROJ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>